#Spring Cloud Configuration

#Port Number
server:
  port: 10000

#Eureka Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Spring Boot Configuration
spring:
  output:
    ansi:
      enabled: always
#Rabbit MQ Configuration
  cloud:
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 47.101.45.147
                port: 5672
                username: guest
                password: guest
      bindings:
        adminEventOutput:
          destination: adminEventTopic
          content-type: application/json
          binder: rabbit1