#Spring Cloud Configuration

#port number
server:
  port: 10001

#eureka configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Spring Boot Configuration
spring:
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/shop_admin?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      binders:
        rabbit2:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 47.101.45.147
                port: 5672
                username: guest
                password: guest
      bindings:
        adminEventInput:
          destination: adminEventTopic
          content-type: application/json
          group: adminSessionGroup
          binder: rabbit2
  redis:
    host: 47.101.45.147
    port: 6379
    session:
      store-type: redis