#Spring Cloud Configuration

#Port Number
server:
  port: 5555

#Eureka Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Hystrix Configuration
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000

#Ribbon Configuration
ribbon:
  ReadTimeout: 7000

#Zuul Configuration
zuul:
  sensitive-headers:
  add-host-header: true
  ignored-services: '*'
  prefix: /api
  routes:
    adminregisterservice: /ar/**
    userregisterservice: /ur/**
    adminsessionservice: /as/**
    usersessionservice: /us/**
    adminnewsservice: /an/**
    usernewsservice: /un/**
    adminproductservice: /ap/**
    userproductservice: /up/**

#Spring Boot Configuration
spring:
  output:
    ansi:
      enabled: always
#Spring Session Redis Configuration
  redis:
    host: 47.101.45.147
    port: 6379
  session:
    store-type: redis