#Spring Cloud Configuration

#Port Number
server:
  port: 10003

#Eureka Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Spring Boot Configuration
spring:
  output:
    ansi:
      enabled: always
#JPA Configuration
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/shop_news?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#Rabbit MQ Configuration
  cloud:
    stream:
      binders:
        rabbit4:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 47.101.45.147
                port: 5672
                username: guest
                password: guest
      bindings:
        newsEventInput:
          destination: newsEventTopic
          content-type: application/json
          group: newsGroup
          binder: rabbit4