#Spring Cloud Configuration

#Port Number
server:
  port: 10010

#Eureka Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Spring Boot Configuration
spring:
  output:
    ansi:
      enabled: always
  #JPA Configuration
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  #Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/shop_order?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Rabbit MQ Configuration
  cloud:
    stream:
      binders:
        rabbit10:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 47.101.45.147
                port: 5672
                username: guest
                password: guest
      bindings:
        orderEventInput:
          destination: orderEventTopic
          content-type: application/json
          group: orderGroup
          binder: rabbit10
  #Spring Session Redis Configuration
  redis:
    host: 47.101.45.147
    port: 6379
  session:
    store-type: redis