#Spring Cloud Configuration

#Port Number
server:
  port: 10009

#Eureka Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Spring Boot Configuration
spring:
  output:
    ansi:
      enabled: always
  #Spring Session Redis Configuration
  redis:
    host: 47.101.45.147
    port: 6379
  session:
    store-type: redis